In [1]:
# importing numpy

import numpy as np

In [2]:
# creating array objects with numpy

a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
# accessing the elements

print(a[1])

2


In [4]:
# We also have a Python List. What's so special about numpy array?

# Benefits of usign numpy array over a python list,
# 1. Less memory
# 2. Fast
# 3. Convenient 

In [5]:
# Comparing numpy with a python list

import time
import sys

In [8]:
l = range(1000)
print(sys.getsizeof(5)*len(l)) # In the given code, the 5 is being used as a placeholder to represent an integer. This code attempts to calculate the total memory usage (in bytes) for a list of 1000 integers, assuming that each integer takes the same amount of memory as the integer 5

28000


In [11]:
array = np.arange(1000)
print(array.size)
print(array.size*array.itemsize)

1000
4000


In [12]:
# SO, from the above example we can see that, numpy array taking 4000 byte memory whereas, python list taking 28000 byte.

In [16]:
SIZE = 10000000
l1 = range(SIZE)
l2 = range(SIZE)

a1 = np.arange(SIZE)
a2 = np.arange(SIZE)

# python list
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("python list took: ", (time.time() - start)*1000)


# numpy array
start = time.time()
result = a1 + a2
print("numpy took: ", (time.time()-start)*1000)

python list took:  2587.4154567718506
numpy took:  317.57259368896484


In [17]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
a1 + a2

array([5, 7, 9])

In [18]:
a2 - a1

array([3, 3, 3])

In [19]:
a1*a2

array([ 4, 10, 18])

In [20]:
a1/a2

array([0.25, 0.4 , 0.5 ])

In [21]:
# numpy : basic array operations

import numpy as np
a = np.array([5,6,9])
a[0]

5

In [24]:
a = np.array([[1,2],[3,4],[5,6]])
a.shape

(3, 2)

In [25]:
a.ndim    # tells the dimensions of an array

2

In [26]:
a.itemsize

4

In [27]:
a.dtype

dtype('int32')

In [29]:
a = np.array([[1,2],[3,4],[5,6]], dtype = np.float64)
a.itemsize

8

In [30]:
a.size # Total no. of elements

6

In [31]:
a = np.array([[1,2],[3,4],[5,6]], dtype = complex)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [32]:
a.itemsize

16

In [34]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
l = range(5)
l

range(0, 5)

In [37]:
l[0]

0

In [38]:
l[1]

1

In [39]:
np.arange(1,5)

array([1, 2, 3, 4])

In [41]:
np.arange(1,7,2)

array([1, 3, 5])

In [42]:
np.linspace(1,5,10)      # It generate 10 number which is linearly spaced.

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

"Linearly spaced" refers to a sequence of values that are equally spaced at constant intervals. In mathematics and programming, creating a linearly spaced sequence means that the difference between consecutive values is the same.

In [43]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [44]:
a.shape

(3, 2)

In [45]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [47]:
a.ravel()     # making the array one dimensional

array([1, 2, 3, 4, 5, 6])

In [48]:
a         # All the above operations, It doesn't going to Alter original array.

array([[1, 2],
       [3, 4],
       [5, 6]])

In [49]:
a.min()

1

In [50]:
a.max()

6

In [51]:
a.sum()

21

In [52]:
a.sum(axis = 0)

array([ 9, 12])

In [54]:
a.sum(axis = 1)

array([ 3,  7, 11])

In [55]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [56]:
np.std(a)   # standard deviation

1.707825127659933

In [58]:
# Some Basic Mathematical Operations

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [59]:
a

array([[1, 2],
       [3, 4]])

In [60]:
b

array([[5, 6],
       [7, 8]])

In [61]:
a+b

array([[ 6,  8],
       [10, 12]])

In [62]:
# matrix multiplication

a.dot(b)

array([[19, 22],
       [43, 50]])

In [63]:
a*b

array([[ 5, 12],
       [21, 32]])

In [64]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [65]:
# numpy: slicing/stacking and indexing wiht boolean arrays

In [66]:
# indexing and Slicing

n = [6,7,8]
n[0:2]

[6, 7]

In [68]:
n[-1:]

[8]

In [69]:
n[-1]

8

In [70]:
a = np.array([6,7,8])
a[0:2]

array([6, 7])

In [71]:
a[-1]

8

In [72]:
a = np.array([[6,7,8],[1,2,3],[9,3,2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [73]:
a[1,2]

3

In [74]:
a[0:2]

array([[6, 7, 8],
       [1, 2, 3]])

In [75]:
a[0:2,2]   # 2nd Element of 0th row and 1st row

array([8, 3])

In [76]:
a[-1]

array([9, 3, 2])

In [77]:
a[-1,0:2]

array([9, 3])

In [79]:
a[:,1:3]  

array([[7, 8],
       [2, 3],
       [3, 2]])

In [80]:
# Iterate through an array

a = np.array([[6,7,8],[1,2,3],[9,3,2]])
a


array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [81]:
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [82]:
for cell in a.flat:
    print(cell)

6
7
8
1
2
3
9
3
2


In [84]:
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [86]:
b = np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [87]:
np.vstack((a,b))  # vertical stacking

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [88]:
np.hstack((a,b))  # horizontal stacking

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [90]:
a = np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [91]:
# vertical slicing into three equal sized arrays

np.hsplit(a,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [92]:
result = np.hsplit(a,3)

In [93]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [94]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [95]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [99]:
result = np.vsplit(a,2)

In [97]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [98]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [109]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [110]:
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [111]:
a[b] # wherever it found true in b it return those elements from the original array

array([ 5,  6,  7,  8,  9, 10, 11])

In [112]:
a[b] = -1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [114]:
# Iterarte through numpy array

a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [115]:
for row in a:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [116]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [118]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [119]:
# numpy.nditer

for x in np.nditer(a,order='c'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [120]:
for x in np.nditer(a,order='F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [122]:
for x in np.nditer(a,order='F',flags = ['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [124]:
for x in np.nditer(a,op_flags = ['readwrite']):
    x[...] = x*x

In [125]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [127]:
# iterating through two numpy array simultaneously

b = np.arange(3,15,4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [128]:
for x,y in np.nditer([a,b]):
    print(x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
